@CoreBanking.API_HostAddress = https://localhost:7205

GET {{CoreBanking.API_HostAddress}}/api/v1/corebanking/customers
Accept: application/json

###

POST {{CoreBanking.API_HostAddress}}/api/v1/corebanking/customers
Content-type: application/json

{
  "Id" : "00000000-0000-0000-0000-000000000000",
  "Name": "",
  "Address": "nam dinh"
}
###